#pragma once

#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

#include "inferx/core/status.h"

namespace inferx::tokenizer {

/// \brief A byte-level BPE tokenizer, loaded from a HuggingFace
///        `tokenizer.json`.
///
/// ARCHITECTURE.md §9 nominates `tokenizers-cpp` -- the real Rust
/// implementation behind a C FFI -- and R7 argues for it on the grounds that
/// exactness with HuggingFace is the risk, and FFI makes exactness hold by
/// construction rather than by assertion.  This is a deliberate departure from
/// that, taken to keep a Rust toolchain and a static-library link out of the
/// build, and it accepts the consequence R7 names: correctness here is a claim
/// that has to be *tested*, not one the design guarantees.
///
/// The test is `tests/unit/tokenizer_conformance_test.cc`, which replays a
/// corpus generated by HuggingFace's own tokenizer and requires exact token-id
/// equality on every string in it.  If that test ever fails on input we cannot
/// fix, the FFI is the fallback, and this class's interface is small enough on
/// purpose that swapping the implementation underneath it is contained.
///
/// What is implemented is the pipeline Qwen2's `tokenizer.json` actually
/// declares, and nothing else:
///
///   * added-token extraction, leftmost-longest, ahead of everything;
///   * NFC normalization;
///   * a GPT-2 style pre-tokenizer split, hand-written because the pattern
///     needs `\p{L}`, `\p{N}` and a lookahead;
///   * byte-level mapping of each piece to the 256-character alphabet;
///   * BPE by merge rank;
///   * a byte-level decoder.
///
/// Loading a different model's tokenizer is checked, not assumed: `Load` fails
/// if the file declares a normalizer, pre-tokenizer or decoder this does not
/// implement, rather than silently tokenizing it wrongly.
///
/// Thread-safety: `const` methods are safe to call concurrently.  There is no
/// memoization of BPE words for that reason -- prompt encoding is far from the
/// hot path, and a shared cache would need a lock that costs more than it saves.
class Tokenizer {
 public:
  /// \brief Loads from a `tokenizer.json` path.
  static StatusOr<std::unique_ptr<Tokenizer>> LoadFromFile(
      const std::string& path);

  /// \brief Loads `<dir>/tokenizer.json`.
  static StatusOr<std::unique_ptr<Tokenizer>> LoadFromDirectory(
      const std::string& dir);

  /// \brief Encodes `text`, extracting added tokens from it.
  ///
  /// This is the path for prompts the *engine* builds, where `<|im_start|>` in
  /// the string is meant as the control token.  Text that came from an end user
  /// should go through `EncodeOrdinary` instead, so that a user who types
  /// `<|im_end|>` cannot end the turn.
  std::vector<int32_t> Encode(std::string_view text) const;

  /// \brief Encodes `text` with added tokens treated as ordinary characters.
  std::vector<int32_t> EncodeOrdinary(std::string_view text) const;

  /// \brief Decodes `ids` back to text.
  ///
  /// \param skip_special Drop tokens marked special rather than emitting their
  ///                     literal content.
  std::string Decode(const std::vector<int32_t>& ids,
                     bool skip_special = false) const;

  /// \brief The number of ids the tokenizer can produce.
  ///
  /// This is the base vocabulary plus added tokens, and is *not* the model's
  /// `vocab_size`, which is padded up to a round number -- Qwen2.5 has 151665
  /// tokens and a 151936-wide embedding.  Rows in between are unreachable.
  int32_t VocabSize() const { return static_cast<int32_t>(id_to_token_.size()); }

  /// \brief The id of `token`, or nullopt if it is not in the vocabulary.
  std::optional<int32_t> TokenToId(std::string_view token) const;

  /// \brief The surface form of `id`, or an empty view if out of range.
  std::string_view IdToToken(int32_t id) const;

  /// \brief Whether `id` is an added token marked special.
  bool IsSpecial(int32_t id) const;

  /// \brief The end-of-sequence id declared by the checkpoint.
  int32_t eos_id() const { return eos_id_; }

  /// \brief The Unicode version of the tables this was built against.
  static const char* UnicodeVersion();

 private:
  Tokenizer() = default;

  // A token added on top of the BPE vocabulary, matched in the raw text before
  // normalization or pre-tokenization.
  struct AddedToken {
    std::string content;
    int32_t id = 0;
    bool special = false;
  };

  // Splits `text` on added tokens, appending ids for the tokens and encoding
  // the spans between them.
  void EncodeWithAddedTokens(std::string_view text,
                             std::vector<int32_t>* out) const;

  // Normalize, pre-tokenize, byte-level, BPE.
  void EncodeSpan(std::string_view text, std::vector<int32_t>* out) const;

  // Applies merges to one byte-level word, appending its ids.
  void ApplyBpe(const std::string& word, std::vector<int32_t>* out) const;

  std::vector<std::string> id_to_token_;
  std::unordered_map<std::string, int32_t> token_to_id_;

  // Merge rank, keyed on the two halves joined by a space -- the same key the
  // file uses.  A space can never occur inside a byte-level token (byte 0x20
  // maps to U+0120), so the key is unambiguous.
  std::unordered_map<std::string, int32_t> merge_rank_;

  std::vector<AddedToken> added_;
  std::unordered_map<int32_t, bool> added_special_;

  int32_t eos_id_ = -1;

  friend class IncrementalDecoder;
};

/// \brief Decodes a token stream incrementally, holding back partial
///        characters.
///
/// Streaming needs this because a token boundary is not a character boundary.
/// One BPE token can carry the first two bytes of a three-byte character, and a
/// naive per-token decode would put U+FFFD into the stream where a batch decode
/// of the same ids has none -- so the streamed text would not match the text
/// the non-streaming endpoint returns for the same completion.
///
/// `Push` returns only bytes that are known-complete; anything else is retained
/// until a later token completes it, or until `Flush`.
class IncrementalDecoder {
 public:
  /// \param tokenizer      Borrowed; must outlive this object.
  /// \param skip_special   Drop special tokens instead of emitting them.
  explicit IncrementalDecoder(const Tokenizer* tokenizer,
                              bool skip_special = true);

  /// \brief Adds one token, returning the text that is now safe to emit.
  std::string Push(int32_t id);

  /// \brief Returns any retained bytes, ending the stream.
  ///
  /// A partial sequence still held at this point is genuinely truncated input,
  /// so it is emitted as-is and will decode to U+FFFD -- which is what a batch
  /// decode of the same truncated ids would also produce.
  std::string Flush();

 private:
  const Tokenizer* tokenizer_;
  bool skip_special_;
  std::string pending_;
};

}  // namespace inferx::tokenizer
